Integration Covalent historical API
gigliagustin/exchange-web pull request #1
Opened 2022-09-24 19:36 UTC by castromaciel

We made the first integration and add an example of how to use the Covalent API.

2022-09-25 20:31 UTC, gigliagustin requested changes
Hi Maciel,

To approve this PR, you have to review the comments that I leaved. Please, review it, make the changes and make the PR again.

2022-09-27 03:46 UTC, castromaciel commented on src/services/getHistorical.js
> +// const date = new Date().now();
Mr Agucho, I've made another commit with the requested changes.

2022-09-27 03:46 UTC, castromaciel commented on src/services/getHistorical.js
> +// const from = date; // Restar 7 dias;
Mr Agucho, I've made another commit with the requested changes.

2022-09-27 18:53 UTC, gigliagustin approved these changes
Thanks for making the changes dear Macielacho!

2022-09-27 18:53 UTC, merged